[package]
name = "relay"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]



[dependencies.tracing]
version = "0.1.35"


[dependencies.tokio]
version = "1.19.0"
features = ["full"]