[package]
name = "croc_rewrite"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
spake2 = { version = "0.3.1", features = ["std"] }
bincode = "1.3.3"